@startuml

class Game {
    -players: Player[]
    -board: Board
    -dice: Dice
    -currentPlayer: Player
    -currentTurn: int
    +createBoard()
    +createDice()
    +addPlayer()
    +startGame()
    +nextTurn()
}

class Player {
    -name: String
    -figure: Figure
    -currentTile: Tile
    +move(int steps)
    +setTile(Tile tile)
}

class Figure {
    -color: String
    +Figure(String color)
    +getColor()
}

class Board {
    -startTile: Tile
    -endTile: Tile
    -tiles: HashMap<int, Tile>
    +Board()
    +getTile(int index): Tile
    +addTile(Tile tile)
    +getStartTile()
    +getEndTile()
}

class Dice {
    -die: int
    +Dice(int die)
    +roll()
}

class Tile {
    -action: TileAction
    -nextTile: Tile
    +Tile(TileAction action, Tile nextTile)
    +placePlayer(Player player)
    +removePlayer(Player player)
    +getAction()
    +getNextTile()
}

class TileAction {
    -action: String
    +TileAction(String action)
    +execute(Player player)
    +getAction()
}

class LadderAction {
    -action: String
    -destination: Tile
    +LadderAction(String action, Tile destination)
    +execute(Player player)
    +getAction()
}

Game --> Player
Game --> Board
Game --> Dice
Player --> Figure
Board --> Tile
Tile --> TileAction
TileAction --|> LadderAction
LadderAction --> Tile
Player --> Tile

@enduml