@startuml

class Game {
    -players: Player[]
    -board: Board
    -dice: Dice
    -currentPlayer: Player
    -currentTurn: int
    +createBoard()
    +createDice()
    +addPlayer()
    +startGame()
    +nextTurn()
}

class Player {
    -name: String
    -figure: Figure
    -currentTile: Tile
    +move(int steps)
    +setTile(Tile tile)
}

class Figure {
    -color: String
    +getColor()
}

class Board {
    -tiles: HashMap<int, Tile>
    +getTile(int index): Tile
    +addTile(Tile tile)
}

class Dice {
    -die: int
    +roll()
}

class Tile {
    -action: TileAction
    -nextTile: Tile
    +placePlayer(Player player)
    +removePlayer(Player player)
    +getAction()
    +getNextTile()
}

class TileAction {
    -action: String
    +execute(Player player)
}

class LadderAction {
    -action: String
    -destination: Tile
    +execute(Player player)
}

Game --> Player
Game --> Board
Game --> Dice
Player --> Figure
Board --> Tile
Tile --> TileAction
TileAction --|> LadderAction
LadderAction --> Tile
Player --> Tile

@enduml